---
- name: Monitor file system usage and send email notification
  hosts: all
  become: true

  vars:
    threshold_percent: 90
    recipient_email: "recipient@example.com"
    sender_email: "sender@example.com"

  tasks:
    - name: Get file system usage
      shell: df -h
      register: df_output

    - name: Parse file system usage
      set_fact:
        fs_usage: "{{ df_output.stdout_lines[1:] | map('regex_replace', '^\\S+\\s+\\S+\\s+\\S+\\s+\\S+\\s+(\\S+)%\\s+\\S+$', '\\1') | list }}"

    - name: Check file system usage
      debug:
        msg: "File system {{ item.0 }} usage is {{ item.1 }}%"
      loop: "{{ query('zip', df_output.stdout_lines[1:], fs_usage) }}"
      when: item.1 | int > threshold_percent

    - name: Send email notification
      shell: "echo 'File system usage is high' | sendmail -F '{{ sender_email }}' -f '{{ sender_email }}' '{{ recipient_email }}'"
      when: df_output.stdout_lines is defined and df_output.stdout_lines | length > 1 and fs_usage | map('int') | any > threshold_percent
