- hosts: all
  tasks:
    - name: Display file systems with more than 80% usage
      shell: 'df -h | awk ''NR>1 && $5 > 80 {print}'' | sed ''s/^ *//g'''
      register: disk_usage

    - debug:
        var: disk_usage.stdout_lines
