- name: Check file system usage
  hosts: all
  vars:
    threshold: 80  # Change this value to set the threshold percentage
    email_recipient: "user@example.com"  # Change this value to set the email recipient
  tasks:
    - name: Get file system usage
      shell: df -h
      register: df_output

    - name: Filter file systems above threshold
      set_fact:
        above_threshold: "{{ df_output.stdout_lines | select('match', '^(.+\\s+){4}\\d+%(\\s+.+)?$') | select('match', '\\d+%(\\s+.+)?$') | select('split', '%') | select('int') | select('gt', threshold) | list }}"

    - name: Create file with above threshold file systems
      shell: echo "{{ above_threshold | join('\\n') }}" > /tmp/filesystems_above_threshold.txt

    - name: Send email with file attachment
      shell: "sendmail -t < /tmp/mail.txt"
      args:
        stdin: "{{ lookup('template', 'mail.j2') }}"
      delegate_to: localhost
