---
- name: Monitor file system usage
  hosts: all
  
  vars:
    # set the threshold in percentage (example: 80%)
    threshold: 80
    # set the log file path on the Ansible server
    log_file: "/var/log/file_system_usage.log"
  
  tasks:
    - name: Get file system usage
      shell: df -h | awk '{print $1 " " $5 " " $6}' | sed '1d'
      register: df_output
  
    - name: Check file system usage
      set_fact:
        usage_exceeded: true
      when: item.split()[1] | int > threshold
      loop: "{{ df_output.stdout_lines }}"
  
    - name: Copy usage details to log file
      lineinfile:
        line: "{{ ansible_hostname }}: {{ item }}"
        path: "{{ log_file }}"
      when: usage_exceeded is defined
      loop: "{{ df_output.stdout_lines }}"
