---
- name: Check File system Space Usage more than 30%
  hosts: all
  tasks:
          - name: Display file systems with more than 30% usage
            shell: df -P | awk '0+$5 >= 30 {print}'
            register: disk_usage  
          - debug:
                  var: disk_usage.stdout_lines   

          - name: Write debug output to file on control node
            copy:
              content: |
                {{ inventory_hostname }} filesystem usage more than 30%:
                {{ disk_usage.stdout }}   
              dest: /tmp/file-system-usage.txt
            delegate_to: localhost
            when: disk_usage.stdout_lines | length > 0   
