---
- name: Check File system Space Usage more than 30%
  hosts: all
  tasks:
          - name: Display file systems with more than 30% usage
            shell: df -P | awk '0+$5 >= 30 {print}'
            register: disk_usage  
          - debug:
                  var: disk_usage.stdout_lines   

          - name: Create file if it doesn't exist      
            file:
              path: /tmp/file-system-usage.txt
              state: touch
            delegate_to: localhost
            when: not ansible_check_mode     

          - name: Append debug output to file on control node
            lineinfile:
              line: |
                {{ inventory_hostname }} filesystem usage more than 30%:
                {{ disk_usage.stdout }}   
              path: /tmp/file-system-usage.txt
              insertafter: EOF
            delegate_to: localhost
            when: disk_usage.stdout_lines | length > 0    

          - name: Send mail notification 
            shell: |
              (echo "Subject : File Systems Usage morethan 80%"; cat /tmp/file-system-usage.txt) |  /usr/sbin/sendmail -vf FINTRAN_CLOUD_DBA_INFRA@list.att.com gp085c@att.com
            args: 
              executable: /bin/bash  
            delegate_to: localhost
