---
- name: Monitor file system usage and send email notification
  hosts: your-remote-host
  become: true
  vars:
    email_sender: your_email_sender@your_domain.com
    email_recipient: your_email_recipient@your_domain.com
    ansible_server_hostname: "{{ ansible_hostname }}"
    threshold_percent: 90

  tasks:
    - name: Get file system usage
      shell: df -h /
      register: df_output

    - name: Check if usage is beyond threshold
      set_fact:
        usage_beyond_threshold: "{{ (df_output.stdout_lines[1].split()[4] | int) > threshold_percent }}"
      when: df_output.stdout_lines[1].split()[4] != "Use%"

    - name: Send email notification
      command: /usr/sbin/sendmail -t -oi -oem -f "{{ email_sender }}"
      args:
        stdin: |
          To: {{ email_recipient }}
          From: {{ email_sender }}
          Subject: File system usage report for {{ ansible_server_hostname }}

          The file system usage on {{ ansible_server_hostname }} is:

          {{ df_output.stdout }}

          This email was sent from the Ansible server.

      when: usage_beyond_threshold
