---
- name: Check File System Usage and Send Notification
  hosts: your_servers
  gather_facts: yes

  vars:
    threshold_limit: 80   # Change this value to set the threshold limit for file system usage
    email_sender: "sender@example.com"
    email_recipients: "recipient1@example.com, recipient2@example.com"

  tasks:
    - name: Get File System Usage
      shell: df -h
      register: df_output

    - name: Check if File System Usage is beyond Threshold Limit
      set_fact:
        usage_beyond_threshold: "{{ item.split()[4] | int > threshold_limit }}"
      when: "'/dev/' in item"
      loop: "{{ df_output.stdout_lines }}"

    - name: Send Notification if File System Usage is beyond Threshold Limit
      when: usage_beyond_threshold
      block:
        - name: Create Mail Body
          set_fact:
            mail_body: |
              Hostname: {{ ansible_hostname }}
              File System Usage is beyond threshold limit of {{ threshold_limit }}%
              {{ df_output.stdout }}

        - name: Send Mail Notification
          shell: echo "{{ mail_body }}" | /usr/sbin/sendmail -t -f "{{ email_sender }}" -- "{{ email_recipients }}"
