---
- name: Check file system usage and send email notification
  hosts: all
  gather_facts: true
  become: true

  vars:
    threshold_percentage: 90
    email_recipient: user@example.com
    email_subject: File system usage exceeded threshold
    email_body: |
      The following file systems are currently above {{ threshold_percentage }}% usage:

      {% for fs in fs_list %}
      {{ fs.mount }}: {{ fs.percent }}%
      {% endfor %}

  tasks:
    - name: Get file system usage
      shell: df -h
      register: df_output

    - name: Parse file system usage
      set_fact:
        fs_list: "{{ df_output.stdout_lines[1:] | map('regex_replace', '^(\\S+\\s+){5}', '') | map('regex_replace', '\\s+', ',') | map('split', ',') | map('list') | map('zip_longest', ['filesystem', 'size', 'used', 'available', 'percent', 'mount']) | map('from_entries') | selectattr('percent|int', '>', threshold_percentage) | list }}"

    - name: Send email notification
      shell: "echo '{{ email_body }}' | sendmail -t"
      when: fs_list | length > 0
      vars:
        sendmail_path: "/usr/sbin/sendmail"
        sendmail_command: "{{ sendmail_path }} -oi -t -f {{ ansible_facts['network']['hostname'] }}"
        email_headers: "To: {{ email_recipient }}\nSubject: {{ email_subject }}\nFrom: {{ ansible_facts['network']['hostname'] }}"

      register: sendmail_output

    - name: Debug sendmail output
      debug:
        var: sendmail_output.stdout_lines
      when: sendmail_output.rc != 0
