---
- name: Check file system usage and send email notification
  hosts: all
  become: true

  vars:
    threshold_percent: 90
    recipient_email: "recipient@example.com"
    sender_email: "sender@example.com"

  tasks:
    - name: Check file system usage
      shell: df -h | awk '{if(NR>1)print $5,$6}' | sed 's/%//'
      register: usage_output

    - name: Send email notification
      command: "echo 'File system usage is high on {{ ansible_hostname }}' | sendmail -F '{{ sender_email }}' -f '{{ sender_email }}' '{{ recipient_email }}'"
      when: usage_output.stdout_lines | map('split', ' ') | select('last') | map('int') | list | max > threshold_percent
