---
- name: Check disk usage and send email
  hosts: your_host_name

  vars:
    # Define the threshold in percentage
    disk_threshold: 90
    # Define the email sender and receiver addresses
    email_sender: "your_sender_email_address"
    email_receiver: "your_receiver_email_address"
    # Get the hostname
    hostname: "{{ inventory_hostname }}"

  tasks:
    - name: Get disk usage
      shell: "df -hT"
      register: df_output

    - name: Check disk usage and send email
      when: "'Filesystem' not in item"
      # Exclude the header row of the `df -hT` output
      loop: "{{ df_output.stdout_lines }}"
      set_fact:
        # Extract filesystem, size, used, available, use%, mounted on information
        filesystem: "{{ item.split()[0] }}"
        size: "{{ item.split()[1] }}"
        used: "{{ item.split()[2] }}"
        available: "{{ item.split()[3] }}"
        use_percent: "{{ item.split()[4] }}"
        mount_point: "{{ item.split()[5] }}"
      # Check if usage is beyond threshold and send email
      run_once: true
      command: "/usr/sbin/sendmail -t"
      args:
        stdin: "To: {{ email_receiver }}\nFrom: {{ email_sender }}\nSubject: Disk usage warning on {{ hostname }}\n\nFilesystem: {{ filesystem }}\nSize: {{ size }}\nUsed: {{ used }}\nAvailable: {{ available }}\nUse%: {{ use_percent }}\nMount Point: {{ mount_point }}"
      when: use_percent | int > disk_threshold
