---
- name: Check File system Space Usage
  hosts: all
  tasks:
          - name: Display file systems with more than 10% usage
            shell: df -P | awk '0+$5 >= 30 {print}'
            register: disk_usage  
          - debug:
                  var: disk_usage.stdout_lines
