---
- name: Check file system usage and send mail notification
  hosts: all
  vars:
    threshold_limit: 80  # Set the threshold limit for file system usage
    mail_recipient: user@example.com  # Set the email recipient
    mail_sender: ansible@{{ ansible_fqdn }}  # Set the email sender
  tasks:
    - name: Check file system usage
      shell: df -h
      register: df_output

    - name: Capture file systems beyond threshold limit
      set_fact:
        high_fs: "{{ high_fs|default([]) + [item] }}"
      loop: "{{ df_output.stdout_lines[1:] }}"
      when: item.split()[-2] | int > threshold_limit

    - name: Send mail notification for high file systems
      command: "/usr/sbin/sendmail -t"
      args:
        stdin_lines:
          - "To: {{ mail_recipient }}"
          - "From: {{ mail_sender }}"
          - "Subject: High file system usage on {{ inventory_hostname }}"
          - ""
          - "The following file systems are beyond the threshold limit:"
          - ""
          - "{% for fs in high_fs %}{{ fs }}{% endfor %}"
      when: high_fs is defined and high_fs | length > 0
