---
- name: Monitor File Systems
  hosts: all
  vars:
    threshold_limit: 80
    email_sender: "sender@example.com"
    email_recipient: "recipient@example.com"
  tasks:
    - name: Check File Systems
      shell: df -h
      register: fs_info
    - name: Parse File System Data
      set_fact:
        fs_data: "{{ fs_info.stdout_lines[1:] | map('regex_replace', '( )+', ',') | map('split', ',') | list }}"
    - name: Check Threshold Limit
      set_fact:
        alert_fs: "{{ fs_data | selectattr('4', 'match', threshold_limit) | list }}"
    - name: Send Alert Email
      when: alert_fs | length > 0
      command: echo "File system {{ item.5 }} on {{ inventory_hostname }} is above threshold limit of {{ threshold_limit }}%" | sendmail -s "File System Alert" -r "{{ email_sender }}" "{{ email_recipient }}"
      loop: "{{ alert_fs }}"
