- name: Check Disk Space Usage
  hosts: srv1.example.com
  tasks:
    - name: Disk usage from command module
      command: df -h
      register: space

    - name: Display only file systems beyond threshold limit
      debug:
        msg: "{{ item }}"
      when: item.5|int >= 80   # Modify threshold limit as needed
      with_items: "{{ space.stdout_lines[1:] }}"
