---
- name: Monitor file system usage and send email if high
  hosts: all
  gather_facts: true
  vars:
    threshold_pct: 80
    email_from: "monitoring@example.com"
    email_recipients:
      - "admin@example.com"

  tasks:
    - name: Get file system info
      become: true
      shell: df -h
      register: df_output

    - name: Parse file system info
      set_fact:
        fs_info: "{{ df_output.stdout_lines[1:] | map('regex_replace', '^(\\S+)\\s+(\\S+)\\s+(\\S+)\\s+(\\S+)\\s+(\\S+)\\s+(\\S+)$', '\\1,\\2,\\3,\\4,\\5,\\6') | list }}"

    - name: Check file system threshold
      set_fact:
        high_fs: "{{ fs_info | selectattr('split(',')[4] | int > threshold_pct', 'defined') | list }}"

    - name: Send email if file system usage is high
      command: sendmail -t
      args:
        stdin: |
          Subject: File system usage is high on {{ inventory_hostname }}
          From: {{ email_from }}
          
          The following file systems are above the threshold of {{ threshold_pct }}% usage on {{ inventory_hostname }}:
          {% for fs in high_fs %}
          {{ fs.split(',')[0] }} ({{ fs.split(',')[4] }})
          {% endfor %}
          
          Please take appropriate action to resolve this issue.
        creates: /tmp/sendmail_sent

      when: high_fs|length > 0
